name: Backend CI/CD

on:
  push:
    branches: [ my_new ]  # Change this if your main branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change this to match your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Adjust this command if you use a different test script

    - name: Create deployment package
      run: |
        zip -r deploy.zip . -x "*.git*"  # Exclude unnecessary files

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: backend-artifact
        path: deploy.zip

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}       # Your EC2 public IP
        username: ${{ secrets.EC2_USER }}    # Typically 'ubuntu' for Ubuntu EC2
        key: ${{ secrets.EC2_KEY }}          # Private SSH key stored in GitHub secrets
        port: 22
        script: |
          cd /home/ubuntu/SkillHub-server  # Navigate to the project folder on EC2
          sudo git pull origin my_new   # Pull latest code from main branch
          npm install                 # Install dependencies
          pm2 restart my-app  # Restart the app with PM2
